### ISSUE TITLE
Error when logging in

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#22]
When logging in with my correct credentials I am correctly logged in, but also get the following error:

Login information incorrect. Please try again.

**Comment by kanarb** [comment]
![screen shot 2016-04-04 at 4 36 25 pm](https://cloud.githubusercontent.com/assets/5742093/14267258/90f13fec-fa83-11e5-9159-cfc9ad4da7be.png)

**Comment by NedHenry** [comment]
This was part of issue #15; the error messages from failed login attempts were not being displaying on the login form, so instead those messages stayed on the server and were displayed on the next page you loaded which was configured to display flash messages (in this case, when you successfully logged in). Now that those messages are displaying where they are supposed to, this problem is fixed.
