### ISSUE TITLE
incorrect sorting for 'more recent items'

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#23]
The 'more recent items' link on the homepage is showing results sorted oldest first when it should be newest first.

**Comment by chesleyperry** [comment]
@NedHenry - This can be fixed post-launch, but is the first priority

**Comment by NedHenry** [comment]
This is definitely an issue with the configuration of the solr-search plugin. The way that our theme is integrated with that plugin is kinda problematic because it is really easy to break things like this. I am working on a fix for this problem (hopefully today), and also will be thinking about a way to refactor our code to use solr more robustly in the future.

**Comment by NedHenry** [comment]
I just wanted to say that I hear you that this is the top priority. I am working on it now and making progress, but the solr configuration is a bit subtle and confusing. If I don't have a neat solution by tomorrow, I will implement a short-term workaround so that people don't see confusing results in the mean time.

**Comment by NedHenry** [comment]
This issue has been fixed, and the "more recent items" now displays items sorted by the DateCreated field in descending order. This required modifying the Solr schema and making a few hacks to the SolrSearch plugin, which we should keep in mind when updating that plugin.
