### ISSUE TITLE
Timeline items are showing up in the search results

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#24]
Timeline items are showing up in the search results. They are excluded in the old site.

**Comment by chesleyperry** [comment]
can be fixed post-launch.

**Comment by NedHenry** [comment]
In order to fix this problem (and two other solr-related open issues) I am currently re-indexing the development site (gdao2-dev). If you notice that the site is loading slowly or that search results are wonky for the next few minutes, that is why. I have corrected a few problems with the way the solr plugin was indexing our fields. This should make it possible for me to fix this issue, as well the "more recent items" link and the "subject" field in advanced searches.

**Comment by NedHenry** [comment]
Fixed. These items are now excluded from the Solr index. Let me know if you ever see them on the public side of the site.
