### ISSUE TITLE
Exhibit nav issues

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#25]
The exhibits nav is still having issues. on this page for example the link to 'The End of the Fillmore Series' appears twice. (http://128.114.34.120/exhibits/show/posters/end-of-fillmore)

**Comment by chesleyperry** [comment]
Could this be a theme/style issue?  I think it can be fixed post-launch.

**Comment by NedHenry** [comment]
This is actually not an issue with the theme/styling (except that it has changed slightly), but rather with the exhibit curation. We have defined this exhibit such that there are several empty pages with subpages that share the same name. The theme is set up to automatically display the first child page if possible. I do not know why it was set up like this; perhaps older version of the exhibit builder plugin required this structure for some kind of display workaround? I am trying to not only fix the bug but also create a less hacked up exhibit structure so that these bugs don't recur whenever we upgrade anything. 

I have altered the exhibit in the development version, eliminating empty pages with identical names to their children. You can compare the updated version with the old version using the links below, and let me know if you see any problem with changing the exhibit this way. I have never done any exhibit curation, so I would appreciate some oversight before pushing this change to the production version (might it affect any of the other exhibit page navigation functions?). If this works for y'all, it seems like a fine solution for now. 
We might want to change our theme's display/navigation structure if we add more exhibits, to give exhibit designers more freedom (to take advantage of the features offered by the newer versions of exhibit builder).

updated (dev version): 
http://gdao2-dev.library.ucsc.edu/admin/exhibits/edit/33
http://gdao2-dev.library.ucsc.edu/exhibits/show/posters
old (prod version, not yet updated): 
http://128.114.34.120/admin/exhibits/edit/33
http://128.114.34.120/exhibits/show/posters

**Comment by kanarb** [comment]
Looks good to me.

**Comment by NedHenry** [comment]
I couldn't find any problems with this fix, so I propogated it onto the production version. We can continue to improve the navigation experience as needed.
