### ISSUE TITLE
subject filters are actually filtering on title

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#27]
It looks like subject filters are actually filtering on title. Compare these two searches:

```
 - http://www.gdao.org/solr-search/results/?solrq=260_s:%22Deadheads%20\%28Music%20fans\%29%22

 - http://128.114.34.120/solr-search/results/index?q=260_s:Deadheads+%28Music+fans%29
```

**Comment by chesleyperry** [comment]
This looks like a solr issue.  It can be fixed post-launch.

**Comment by NedHenry** [comment]
I believe I have fixed this on the dev version by altering the query keywords on the advanced search form. 
I think in the future that we should alter this form to use Omeka's search functionality instead of Solr's. It is more appropriate to an advanced search because it is more complete and has a better interface pre-built, and because speed is less of an issue.
