### ISSUE TITLE
404 results in omeka error instead of 404 error

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#28]
When the page is not found it results in an Omeka error instead of a 404 error. Compare:

```
- http://www.gdao.org/fdgbrg
- http://128.114.34.120/fdgbrg
```

**Comment by NedHenry** [comment]
Fixed. This one had to wait until the cloning was complete. Thanks for the reminder.

**Comment by NedHenry** [comment]
Note on this issue for future reference: this is one of the few changes that is not synced between the development and production versions. This is because Omeka is configured to display a nice 404 page in production environments, and to give an informative omeka-specific error page for developers in development environments. What I did to fix the problem was to put the production instance of Omeka into production mode, causing it to load 404 pages from the theme. The development instance of Omeka should stay in the development environment, and continue to show us detailed error messages.
