### ISSUE TITLE
Articles, etc. not defined in contribution, did not get migrated

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/gdao-theme#32]
I realize the item for item types that did not get defined in the updated contribution plugin did not get migrated to the new site.  This means many "articles" and "tickets" didn't get migrated.  I've updated the contribution plugin on both gdao2-dev and the to-be live site.  Is there any way to migrate the article items?  There are at least 50 of those. The rest can be done by copying and pasting (which I will do.)

**Comment by NedHenry** [comment]
I have checked several contributed articles which were transferred over successfully. Do you have a link to any contributed article in the live GDAO that did not get migrated to the new site?
Also, when you say that you upgraded the plugin on both the dev and live site, what exactly do you mean? Did you copy in new files? When did this take place? Thanks for the info! In the future if you could make changes only to the dev site and leave the live one alone, that would be awesome. We can migrate changes from the dev site to the live one when we know they are stable.

**Comment by chesleyperry** [comment]
Sorry I didn't update the plugin - I configured it to accept additional item types.  I will only update gdao2-dev from now on.

Here are several items that didn't make it to gdao2-dev from the live gdao.org site:

http://www.gdao.org/admin/items/show/1696292
http://www.gdao.org/admin/items/show/1696282
http://www.gdao.org/admin/items/show/1696093
http://www.gdao.org/admin/items/show/1695847
http://www.gdao.org/admin/items/show/1692930

**Comment by NedHenry** [comment]
Searching the new site for these articles finds them readily enough, except for the most recently contributed ones from the past few weeks. Let me know what made you have trouble finding these. 

I know the URLs have changed, and I believe we agreed that it was not worth a lot of time to keep these consistent, although that is still technically possible if we want to invest that time now. It would probably take me week or so of concerted fiddling to sort out how to change the database this way without destroying any data.

http://www.gdao.org/admin/items/show/1696292 => Just contributed last week
http://www.gdao.org/admin/items/show/1696282 => http://gdao2-dev.library.ucsc.edu/items/show/1695781
http://www.gdao.org/admin/items/show/1696093 => http://gdao2-dev.library.ucsc.edu/items/show/1695970
http://www.gdao.org/admin/items/show/1695847 => http://gdao2-dev.library.ucsc.edu/items/show/1696681
http://www.gdao.org/admin/items/show/1692930 => http://gdao2-dev.library.ucsc.edu/items/show/1692930

**Comment by chesleyperry** [comment]
I did actually search for these but I swear they didn't come up.  I'm not worried about the item numbers changing but they are not listed as contributed items.  I'm not sure why some items are listed as contributed (with the appropriate rights statements and viewable in the admin contributed items menu) and some items are not. Do you understand how they're flagged?

**Comment by NedHenry** [comment]
Hmm...I had not noticed that these were not marked as "contributed" while other contributed items were. That is odd, and I will look into it. 
I don't know what to make of the items showing up on search for me but not for you. If you ever recreate that problem, please send me a link to the search results page. If this only happens for certain query types or term combinations, that might be hard to find but very good to know about.

One relatively innocuous theory is that the search problems might occur because of the underscores in the title. For example, if the title is "1992_Blair Jackson and David Gans At Book Signing" and you search for "1992" and "Blair Jackson", solr might not recognize that the two words "1992" and "Blair" are both part of the title, instead of a third unrelated word "1992_Blair". If this is the problem, there is not a ton we can do about it except edit the titles of contributed items (automatically) to replace all the underscores with spaces. I figure once I sort out whether this underscore thing is actually causing the problem you saw, we can decide whether that might be worthwhile.

**Comment by chesleyperry** [comment]
I think the searching was user error on my part (using the admin search and not the public).  

We still have an issue with making the contributed items show up in that plugin admin space, assigned to the right contributor with the contributed rights info.  I'll open a new issue for that.  This one can be closed.
