### ISSUE TITLE
Restricted content on the media page

### ISSUE THREAD

**Issue by kanarb** [UCSCLibrary/gdao-theme#9]
On this page (http://gdao2-dev.library.ucsc.edu/media) we are displaying restricted contact. Sue said she would look into this.

**Comment by chesleyperry** [comment]
I'm working on this - will fix today

**Comment by NedHenry** [comment]
I noticed today that I saw this error even when I was logged in to Avalon. It looks like Sue had already granted public access to the video in question, so the error was confusing. The problem was just that the iframe URL was slightly wrong. The URL in the iframe corresponded to the digital object containing the video we wanted to embed, rather than the video itself. I fixed the url and the video now loads.
